import { parseSocialLink } from '@varia/core';
import {
  MediaEmbedPayload,
  MessengerEmbedConfig,
  ResolveMediaMessage,
  ResolveMediaResponse,
} from '../types';
import { DEFAULT_MESSENGER_EMBED_CONFIG, STORAGE_KEY_MESSENGER_EMBED } from '../defaults';
import { createMediaEmbedCard } from '../ui/cardRenderer';
import { mediaCache } from '../cache/mediaCache';
import { resolveMediaEmbed } from '../resolvers';

const processedAnchors = new WeakSet<HTMLAnchorElement>();
let activeObserver: MutationObserver | null = null;
let currentConfig: MessengerEmbedConfig = DEFAULT_MESSENGER_EMBED_CONFIG;

/**
 * Loads current configuration from storage
 */
async function loadConfig(): Promise<MessengerEmbedConfig> {
  try {
    if (typeof chrome !== 'undefined' && chrome.storage?.local) {
      const stored = await chrome.storage.local.get(STORAGE_KEY_MESSENGER_EMBED);
      if (stored[STORAGE_KEY_MESSENGER_EMBED]) {
        currentConfig = {
          ...DEFAULT_MESSENGER_EMBED_CONFIG,
          ...stored[STORAGE_KEY_MESSENGER_EMBED],
        };
      }
    }
  } catch {
    // Use defaults
  }
  return currentConfig;
}

/**
 * Scan a DOM container for un-embedded social media links
 */
export async function scanAndInjectEmbeds(
  root: HTMLElement | Document = document,
  config: MessengerEmbedConfig = currentConfig,
): Promise<void> {
  if (!config.enabled) return;

  const anchors = root.querySelectorAll<HTMLAnchorElement>('a[href]');

  for (const anchor of Array.from(anchors)) {
    if (processedAnchors.has(anchor)) continue;
    if (anchor.getAttribute('data-varia-embedded') === 'true') continue;
    if (anchor.closest('.varia-embed-container') || anchor.closest('[data-varia-embed-id]')) continue;

    // Strict chat container scoping: ignore feeds, reels trays, stories, and non-chat UI
    if (!isInsideMessengerChat(anchor)) continue;

    const href = anchor.href;
    if (!href || href.startsWith('javascript:') || href.startsWith('#')) continue;

    // Ignore plain domain preview anchors generated by Messenger (e.g. "x.com", "youtu.be")
    const anchorText = anchor.textContent?.trim().toLowerCase() || '';
    if (
      anchorText === 'x.com' ||
      anchorText === 'twitter.com' ||
      anchorText === 'facebook.com' ||
      anchorText === 'instagram.com' ||
      anchorText === 'youtu.be' ||
      anchorText === 'youtube.com' ||
      anchorText === 'tiktok.com'
    ) {
      processedAnchors.add(anchor);
      anchor.setAttribute('data-varia-embedded', 'true');
      continue;
    }

    const parsed = parseSocialLink(href);
    if (!parsed) continue;

    // Mark as processed
    processedAnchors.add(anchor);
    anchor.setAttribute('data-varia-embedded', 'true');

    // 1. Check Cache (0ms for chat switching)
    const cached = await mediaCache.get(href);
    if (cached) {
      injectCardBelowAnchor(anchor, cached, config);
      continue;
    }

    // 2. Resolve via Background Worker (CORS bypass) with local fallback
    try {
      const payload = await resolveMedia(href, config);
      if (payload) {
        await mediaCache.set(href, payload);
        injectCardBelowAnchor(anchor, payload, config);
      }
    } catch {
      // Ignore resolution errors for individual links
    }
  }
}

/**
 * Request media resolution from background service worker or local resolver
 */
async function resolveMedia(
  url: string,
  config: MessengerEmbedConfig,
): Promise<MediaEmbedPayload | null> {
  try {
    if (typeof chrome !== 'undefined' && chrome.runtime?.sendMessage) {
      const msg: ResolveMediaMessage = {
        type: 'VARIA_RESOLVE_MEDIA',
        url,
      };
      const response = (await chrome.runtime.sendMessage(msg)) as
        | ResolveMediaResponse
        | undefined;
      if (response && response.success && response.data) {
        return response.data;
      }
    }
  } catch {
    // Fallback to local resolution
  }

  return resolveMediaEmbed(url, config);
}

/**
 * Mounts the media card DOM element right below the anchor/bubble
 */
function injectCardBelowAnchor(
  anchor: HTMLAnchorElement,
  payload: MediaEmbedPayload,
  config: MessengerEmbedConfig,
): void {
  // Find surrounding message container by walking up parent tree
  let container: HTMLElement | null = anchor;
  for (let i = 0; i < 6; i++) {
    if (!container.parentElement || container.parentElement === document.body) break;
    container = container.parentElement;
    if (
      container.getAttribute('role') === 'row' ||
      container.getAttribute('role') === 'gridcell' ||
      container.hasAttribute('data-testid')
    ) {
      break;
    }
  }

  // Avoid duplicate injection in the same message block or thread
  if (container && container.querySelector(`[data-varia-embed-id="${payload.id}"]`)) {
    return;
  }

  // Hide Messenger's duplicate static preview thumbnail if present in same bubble
  const nativePreview =
    container?.querySelector<HTMLElement>('a[aria-label*="Attachment" i]') ||
    container?.querySelector<HTMLElement>('div[aria-label*="Attachment" i]') ||
    anchor.parentElement?.parentElement?.querySelector<HTMLElement>('a[aria-label*="Attachment" i]');

  if (nativePreview && nativePreview !== anchor) {
    nativePreview.style.display = 'none';
  }

  const cardElement = createMediaEmbedCard(payload, config);

  // Mount directly below the original message bubble/text block
  const messageBubble =
    anchor.closest('div[dir="auto"]') ||
    anchor.closest('.message-bubble') ||
    anchor.parentElement;

  const mountTarget = messageBubble || anchor;
  mountTarget.insertAdjacentElement('afterend', cardElement);
}

/**
 * Initialize MutationObserver on Messenger DOM
 */
export async function initMessengerEmbedInjector(): Promise<void> {
  if (activeObserver) return;

  await loadConfig();

  // Initial full document scan
  await scanAndInjectEmbeds(document, currentConfig);

  // Debounced observer for dynamically loaded and virtualized chat bubbles
  let debounceTimeout: ReturnType<typeof setTimeout> | null = null;
  const pendingNodes = new Set<HTMLElement>();

  activeObserver = new MutationObserver(mutations => {
    for (const mutation of mutations) {
      for (let i = 0; i < mutation.addedNodes.length; i++) {
        const node = mutation.addedNodes[i];
        if (node && node.nodeType === Node.ELEMENT_NODE) {
          const el = node as HTMLElement;
          // Ignore our own injected cards to avoid redundant scans
          if (!el.classList.contains('varia-embed-container')) {
            pendingNodes.add(el);
          }
        }
      }
    }

    if (pendingNodes.size > 0) {
      if (debounceTimeout) clearTimeout(debounceTimeout);
      debounceTimeout = setTimeout(() => {
        const nodesToScan = Array.from(pendingNodes);
        pendingNodes.clear();
        for (const node of nodesToScan) {
          if (node.isConnected) {
            scanAndInjectEmbeds(node, currentConfig);
          }
        }
      }, 100);
    }
  });

  activeObserver.observe(document.body || document.documentElement, {
    childList: true,
    subtree: true,
  });

  // Listen for config changes from popup
  if (typeof chrome !== 'undefined' && chrome.storage?.onChanged) {
    chrome.storage.onChanged.addListener((changes, area) => {
      if (area === 'local' && changes[STORAGE_KEY_MESSENGER_EMBED]) {
        currentConfig = {
          ...DEFAULT_MESSENGER_EMBED_CONFIG,
          ...changes[STORAGE_KEY_MESSENGER_EMBED].newValue,
        };
        scanAndInjectEmbeds(document, currentConfig);
      }
    });
  }
}

export function stopMessengerEmbedInjector(): void {
  if (activeObserver) {
    activeObserver.disconnect();
    activeObserver = null;
  }
}

/**
 * Guard: validates that the target link is strictly inside a Messenger chat thread,
 * message bubble, or floating chat tab, and NOT in feeds, reels widgets, stories, or sidebars.
 */
export function isInsideMessengerChat(anchor: HTMLAnchorElement): boolean {
  if (typeof window === 'undefined') return true;

  const hostname = window.location.hostname?.toLowerCase() || '';
  const pathname = window.location.pathname?.toLowerCase() || '';

  // 1. If on messenger.com or facebook.com/messages/* (Full Messenger Interface or E2EE):
  if (
    hostname === 'messenger.com' ||
    hostname.endsWith('.messenger.com') ||
    pathname.startsWith('/messages')
  ) {
    return true;
  }

  // 2. If on the main Facebook website (News Feed, Profile, Reels tab, etc.):
  // Strictly reject feeds, reels carousels, stories, marketplace
  if (
    anchor.closest('[role="feed"]') ||
    anchor.closest('[data-pagelet*="Feed"]') ||
    anchor.closest('[data-pagelet*="Reels"]') ||
    anchor.closest('[data-pagelet*="Stories"]') ||
    anchor.closest('[aria-label*="Reels" i]') ||
    anchor.closest('[aria-label*="Stories" i]') ||
    anchor.closest('[aria-label*="Bảng tin" i]')
  ) {
    return false;
  }

  // 3. On main Facebook, it MUST be inside a chat bubble, message row, or popup chat tab
  const isChat =
    anchor.closest('[role="row"]') ||
    anchor.closest('[role="grid"]') ||
    anchor.closest('[role="dialog"]') ||
    anchor.closest('[data-pagelet*="ChatTab" i]') ||
    anchor.closest('[data-pagelet*="Messaging" i]') ||
    anchor.closest('[data-pagelet*="Chat" i]') ||
    anchor.closest('[aria-label*="Messenger" i]') ||
    anchor.closest('[aria-label*="Chat" i]') ||
    anchor.closest('[aria-label*="Tin nhắn" i]') ||
    anchor.closest('[aria-label*="Messages" i]') ||
    anchor.closest('.message-bubble') ||
    anchor.closest('.fbDockChatTabFlyout') ||
    anchor.closest('div[dir="auto"]');

  return Boolean(isChat);
}

